[package]
name = "image-effects-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.95"
base64 = "0.22.1"
image = "0.25.5"

[dependencies.web-sys]
version = "0.3.72"
features = ["console"]